name: compilation

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  compilation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [debian, fedora]
        build_type: [Debug, Release]

    container:
      image: ghcr.io/cosima/access-om3-ci-images/${{matrix.os}}:0.2.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER="mpicc" -DCMAKE_Fortran_COMPILER="mpifort" -DCMAKE_Fortran_FLAGS="-I$MPI_FORTRAN_MOD_DIR" -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
